### ISSUE TITLE
CTA策略初始化 錯誤

### ISSUE THREAD

**Issue by lovexyz520** [vnpy/vnpy_ib#21]
TWS:10.19.1j

CTA策略初始化 出現異常訊號:Your API version does not support fractional share size rules. Please upgrade to a minimum version 163. Trimmed value 79.76 to 79
Exception in thread Thread-24 (run):

**Comment by noranhe** [comment]
API版本不支持该操作，建议升级IB之后再试试看能不能复现这个问题
