### ISSUE TITLE
ERROR 4 10285 您的API版本不支持小数股数量规则。请至少更新至版本至163

### ISSUE THREAD

**Issue by lance52587** [vnpy/vnpy_ib#22]
![6efea86f5e2344b19b1ca7c591fd164](https://github.com/vnpy/vnpy_ib/assets/45159389/36d88f7a-51af-4f19-b3ca-2adaf3bbb817)

复现方式：订阅IDEALPRO交易所的EUR-USD-CASH品种行情。

**Comment by vnpy** [comment]
需要升级ibapi版本了

**Comment by tbradlo** [comment]
same problem for PBR-USD-STK.SMART

**Comment by tbradlo** [comment]
ib_insync seems to update interface 2 years ago
https://github.com/erdewit/ib_insync/commit/5835745dba24bc0162d95404a3c3071d0fa3ba62

ibapi seems not to be maintained actively, there were many updates in ib_incync over the last two years

**Comment by jxhuliqun138** [comment]
> 需要升级ibapi版本了
但是libapi 版本已经2年都没有更新了，请问 这是你们维护的吗
请问该问题是否有解决办法

**Comment by jxhuliqun138** [comment]
> ![6efea86f5e2344b19b1ca7c591fd164](https://user-images.githubusercontent.com/45159389/237885323-36d88f7a-51af-4f19-b3ca-2adaf3bbb817.png)
> 
> 复现方式：订阅IDEALPRO交易所的EUR-USD-CASH品种行情。

哈喽，请问这个问题，你已经解决吗？

**Comment by noranhe** [comment]
可以在API设置中勾选Send Forex market data in compatibility mode in integer units试试看

**Comment by vnpy** [comment]
已经完成支持更新
