### ISSUE TITLE
ibapi内contractDetails字段未更新minSize

### ISSUE THREAD

**Issue by lance52587** [vnpy/vnpy_ib#25]

**Comment by lance52587** [comment]
https://pypi.org/project/ibapi/
9.81.1版
ibapi/contract.py第116行左右，没有minSize

**Comment by lance52587** [comment]
这个版本兼容吗？nautilus-ibapi 1019.1
https://pypi.org/project/nautilus-ibapi/

**Comment by noranhe** [comment]
要去IB官网下载10.19.1版本的ibapi
可参考https://github.com/vnpy/vnpy_ib/blob/main/README.md
