### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by colin-zhou** [vnpy/vnpy_ib#3]
https://github.com/vnpy/vnpy_ib/blob/d85e13da9d99511ba7a3c96e394ab752797e8b63/vnpy_ib/ib_gateway.py#L117
FOT -> FOP

**Comment by youyuanrsq** [comment]
已修复，https://github.com/youyuanrsq/vnpy_ib/commit/1f2aa17497d3307e8a682f1e3df6e6212d3886d7
