### ISSUE TITLE
IB对历史数据的6个月硬限制似乎改成了软限制

### ISSUE THREAD

**Issue by lance52587** [vnpy/vnpy_ib#30]
https://github.com/vnpy/vnpy_ib/compare/main...seraphium:vnpy_ib:main
![2ed6d336a43e904743b90f21fb5681d](https://github.com/vnpy/vnpy_ib/assets/45159389/244541d7-1d6a-4fe9-bcea-0b14429453b4)

**Comment by vnpy** [comment]
vnpy_ib中应该没有对查询数据的范围做额外限制，IB API放开应该就直接可用了，如果发现问题欢迎再留言
