### ISSUE TITLE
请问 可以支持一下 cfd差价合约的交易吗？

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy_ib#40]
比如美股 特斯拉的cfd  合约id 131067756， 最新版的vnpy 我在gui中输入 id无法查询到相应的行情信息。
cfd 差价合约就是 带杠杠的交易品种而已。

**Comment by noranhe** [comment]
已提供支持https://github.com/vnpy/vnpy_ib/pull/45
