### ISSUE TITLE
ConId合约代码合法性检查

### ISSUE THREAD

**Issue by vnpy** [vnpy/vnpy_ib#41]
当用户输入的代码时Conid类型的时候，如果里面有非数字（比如尾部有空格或者其他），会导致与TWS或者IbGateway之间的连接断开，必须重启vnpy。所以优化方向有两个：

1. Conid发送前检查是否是纯数字
2.代码symbol应该去掉两侧可能出现的空格

**Comment by noranhe** [comment]
空格问题已修复https://github.com/vnpy/vnpy_ib/pull/44/files
