### ISSUE TITLE
vnpy_ib 网关每分钟请求一次历史，有时候会出现这个错误，但程序运行正常

### ISSUE THREAD

**Issue by bthuntergg** [vnpy/vnpy_ib#58]
![微信图片_20241003161511](https://github.com/user-attachments/assets/f7db1a8b-4b32-49e8-9976-d2512c2175b9)
我是在策略中每分钟请求标的XAUUSD-USD-CMDTY.SMART历史数据，程序运行一段时间后，有时候会出现这个问题，但运行正常

**Comment by vnpy** [comment]
IB接口的历史数据查询返回速度较慢，如果在上一次查询全部返回前，又发起了新一轮的查询，就可能导致上述问题。

另外load_bar函数仅建议在on_init初始化时调用，而不应该在策略运行时频繁调用。

**Comment by vnpy** [comment]
> > IB接口的历史数据查询返回速度较慢，如果在上一次查询全部返回前，又发起了新一轮的查询，就可能导致上述问题。
> > 另外load_bar函数仅建议在on_init初始化时调用，而不应该在策略运行时频繁调用。
> 
> 那对于生成动态k线有什么好的方案，因为系统自带的k线生成器都是按k线结束才会推送，但实际策略运行时应该时基于动态执行策略的

每次on_tick函数下，调用完self.bg.update_tick(tick)后，可以通过下列代码访问合成中的K线：

`bar = self.bg.bar`
