### ISSUE TITLE
 vnpy_ib 网关有时候ib断线重连最低价会出现  -1 导致计算有误

### ISSUE THREAD

**Issue by bthuntergg** [vnpy/vnpy_ib#59]
![159051d94d6edd1a6d69f454f48f3b5](https://github.com/user-attachments/assets/49c37ce6-ef9e-42fd-a1b3-27178c5e8141)

**Comment by lanceyliao** [comment]
When [IBApi::EWrapper::tickPrice](https://interactivebrokers.github.io/tws-api/interfaceIBApi_1_1EWrapper.html#ae851ec3a1e0fa2d0964c7779b0c89718) and [IBApi::EWrapper::tickSize](https://interactivebrokers.github.io/tws-api/interfaceIBApi_1_1EWrapper.html#a5ac52bbd35c189e4ed684185da869e02) are reported as -1, this indicates that there is no data currently available. Most commonly this occurs when requesting data from markets that are closed. It can also occur for infrequently trading instruments which do not have open bids or offers at that time of the request. To receive frozen quotes (the last available bid/ask recorded by the system) invoke the function [IBApi.EClient.reqMarketDataType](https://interactivebrokers.github.io/tws-api/classIBApi_1_1EClient.html#ae03b31bb2702ba519ed63c46455872b6) with argument 2. Alternatively, to receive "delayed frozen" data from tickers without holding market data subscriptions, specify a market data type of 4. Frozen data is exclusive to default tick types- [Generic Tick Types](https://interactivebrokers.github.io/tws-api/md_request.html#genticks) are not available- and requires market data subscriptions.

https://interactivebrokers.github.io/tws-api/md_receive.html

**Comment by vnpy** [comment]
由于IB支持的交易市场太多，各个市场的细节规则非常繁琐。

这块建议在策略层的on_tick回调函数下根据实际情况进行过滤，gateway接口层不适合做统一处理。
