### ISSUE TITLE
ib产品类型映射里少了指数类型

### ISSUE THREAD

**Issue by OliverYangKe** [vnpy/vnpy_ib#6]
PRODUCT_IB2VT: Dict[str, Product] = {
    "STK": Product.EQUITY,
    "CASH": Product.FOREX,
    "CMDTY": Product.SPOT,
    "FUT": Product.FUTURES,
    "OPT": Product.OPTION,
    "FOT": Product.OPTION,
    "CONTFUT": Product.FUTURES
}

查了下ib的文档
指数应该是
"IND": Product.INDEX

没有的话会导致在录入指数数据时报错

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy_ib/pull/8
